project:
  name: my-ctl
  mode: module
  version: 1.0.4
  description: myctl quick create  project
  author: labelnet
  author_email: labelnet@foxmail.com
  license: labelnet
  python: ">=3.6"
  keywords:
    - my-ctl
  requirements:
    - nuitka
    - requests
    - pytest
    - pyyaml
    - click
    - twine
  build:
    src: my_ctl
    static: static
    environ_static: MY_CTL_STATIC
  entry_points:
    myctl: "my_ctl:cli"
