project:
  name: my-ctl
  mode: module
  version: 1.0.2
  description: myctl quick create  project
  author: labelnet
  author_email: labelnet@foxmail.com
  license: labelnet
  python: '>=3.6'
  keywords:
  - my-ctl
  requirements:
  - nuitka==0.6.17.5
  - requests==2.25.1
  - pytest==6.2.5
  - pyyaml==6.0
  - click==8.0.3
  - twine==3.5.0
  build:
    src: my_ctl
    static: static
    environ_static: MY_CTL_STATIC
  entry_points:
    myctl: 'my_ctl:cli'